name: Build container image
on: push

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mandelbrot-viewer
      REGISTRY: ghcr.io/ldobbelsteen

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the repository
        id: repository-checkout
        uses: actions/checkout@v4

      - name: Build image
        id: image-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Log in to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        if: ${{ github.ref == 'refs/heads/main' }}
        id: image-push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.image-build.outputs.image }}
          tags: ${{ steps.image-build.outputs.tags }}

      - name: Remove untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: ${{ env.IMAGE_NAME }}
          delete-only-untagged-versions: true
